return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    opts = {
        ensure_installed = {
            'bash',
            'c',
            'diff',
            'javascript',
            'lua',
            'luadoc',
            'markdown',
            'markdown_inline',
            'php',
            'python',
            'query',
            'typescript',
            'vim',
            'vimdoc',
        },
        auto_install = true,
        highlight = { enable = true },
        indent = { enable = true },
    },
}
